((lambda ()
   (display "hello world")
   (display (+ 4 2))
   (((lambda (b)
       ((lambda (f)
          (b (lambda (x) ((f f) x))))
        (lambda (f)
          (b (lambda (x) ((f f) x))))))
     (lambda (f)
       (lambda (n)
         (display n)
         (f (+ n 1)))))
    0)))
